name: released

on:
  release:
    types: [published]

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2
        with:
          vt_api_key: a6a747c6d5855803835fc51a116665655adac7e091f00bd49e11f37bc2da4fb0
          github_token: ${{ github.token }}
          files: |
            *.zip
